### ISSUE TITLE
Need to create formal application spec sheet.

### ISSUE THREAD

**Issue by grunklejp** [University-Code/uni-code#1]
I suggest we start by laying out what an optimal v1 of the application would entail and then lay out the specifications accordingly. When we have deployed v1 we can revise the spec for v2 with new features and move on from there. 

Any thoughts on this approach?

**Comment by kailynw** [comment]
Sounds like a plan when is a good day to talk ?

**Comment by grunklejp** [comment]
Don't we have to meet with Wooster to talk about project expectations and such?  Probably after doing that.

**Comment by kailynw** [comment]
O yea let me look at that email real quick...

**Comment by abohlman** [comment]
delete this comment
