### ISSUE TITLE
Remove side bar from base.html

### ISSUE THREAD

**Issue by grunklejp** [University-Code/uni-code#12]
We need to change the base.html so that it only contains the top nav bar. Almost every other html doc should extend base.html which we currently cannot do because of the side bar. 

A possible solution to this would be to put the side bar into its own template snippet. 
Thoughts?

**Comment by kailynw** [comment]
If we use snippets for this it would just be a little harder to find.
Because by time we’re done we will probably have like 30 snippets

**Comment by grunklejp** [comment]
That is true. What do you prepose? having multiple base files?

**Comment by grunklejp** [comment]
I looked at the template docs. We can create a new {% block 'side-bar'%} in the base html doc and go ahead a fill it in with the sidebar. If we make a new page that needs to extend base but doesn't need the side-bar you can just put an empty div in it.

**Comment by grunklejp** [comment]
Or we just do away with the sidebar altogether.

**Comment by kailynw** [comment]
Or you can just say include side bar for certain pages. The only places the
side bar doesn’t really need to be referenced are places like the login
page or something
